export default {
    /************** CENTRO DISTRIBUCION ******************/
    GET_CENTROS_DISTRIBUCION_START: '@ENRUTA:GET_CENTROS_DISTRIBUCION_START',
    GET_CENTROS_DISTRIBUCION_SUCCESS: '@ENRUTA:GET_CENTROS_DISTRIBUCION_SUCCESS',
    GET_CENTROS_DISTRIBUCION_ERROR: '@ENRUTA:GET_CENTROS_DISTRIBUCION_ERROR',

    DELETE_CENTRO_DISTRIBUCION_START: '@ENRUTA:DELETE_CENTRO_DISTRIBUCION_START',
    DELETE_CENTRO_DISTRIBUCION_SUCCESS: '@ENRUTA:DELETE_CENTRO_DISTRIBUCION_SUCCESS',
    DELETE_CENTRO_DISTRIBUCION_ERROR: '@ENRUTA:DELETE_CENTRO_DISTRIBUCION_ERROR',

    CREATE_CENTRO_DISTRIBUCION_START: '@ENRUTA:CREATE_CENTRO_DISTRIBUCION_START',
    CREATE_CENTRO_DISTRIBUCION_SUCCESS: '@ENRUTA:CREATE_CENTRO_DISTRIBUCION_SUCCESS',
    CREATE_CENTRO_DISTRIBUCION_ERROR: '@ENRUTA:CREATE_CENTRO_DISTRIBUCION_ERROR',

    UPDATE_CENTRO_DISTRIBUCION_START: '@ENRUTA:UPDATE_CENTRO_DISTRIBUCION_START',
    UPDATE_CENTRO_DISTRIBUCION_SUCCESS: '@ENRUTA:UPDATE_CENTRO_DISTRIBUCION_SUCCESS',
    UPDATE_CENTRO_DISTRIBUCION_ERROR: '@ENRUTA:UPDATE_CENTRO_DISTRIBUCION_ERROR',

    /************** CLIENTES ******************/
    GET_CLIENTES_START: '@ENRUTA:GET_CLIENTES_START',
    GET_CLIENTES_SUCCESS: '@ENRUTA:GET_CLIENTES_SUCCESS',
    GET_CLIENTES_ERROR: '@ENRUTA:GET_CLIENTES_ERROR',

    DELETE_CLIENTE_START: '@ENRUTA:DELETE_CLIENTE_START',
    DELETE_CLIENTE_SUCCESS: '@ENRUTA:DELETE_CLIENTE_SUCCESS',
    DELETE_CLIENTE_ERROR: '@ENRUTA:DELETE_CLIENTE_ERROR',

    CREATE_CLIENTE_START: '@ENRUTA:CREATE_CLIENTE_START',
    CREATE_CLIENTE_SUCCESS: '@ENRUTA:CREATE_CLIENTE_SUCCESS',
    CREATE_CLIENTE_ERROR: '@ENRUTA:CREATE_CLIENTE_ERROR',

    UPDATE_CLIENTE_START: '@ENRUTA:UPDATE_CLIENTE_START',
    UPDATE_CLIENTE_SUCCESS: '@ENRUTA:UPDATE_CLIENTE_SUCCESS',
    UPDATE_CLIENTE_ERROR: '@ENRUTA:UPDATE_CLIENTE_ERROR',

    /************** RUTA ******************/
    GET_RUTAS_START: '@ENRUTA:GET_RUTAS_START',
    GET_RUTAS_SUCCESS: '@ENRUTA:GET_RUTAS_SUCCESS',
    GET_RUTAS_ERROR: '@ENRUTA:GET_RUTAS_ERROR',

    DELETE_RUTA_START: '@ENRUTA:DELETE_RUTA_START',
    DELETE_RUTA_SUCCESS: '@ENRUTA:DELETE_RUTA_SUCCESS',
    DELETE_RUTA_ERROR: '@ENRUTA:DELETE_RUTA_ERROR',

    CREATE_RUTA_START: '@ENRUTA:CREATE_RUTA_START',
    CREATE_RUTA_SUCCESS: '@ENRUTA:CREATE_RUTA_SUCCESS',
    CREATE_RUTA_ERROR: '@ENRUTA:CREATE_RUTA_ERROR',

    UPDATE_RUTA_START: '@ENRUTA:UPDATE_RUTA_START',
    UPDATE_RUTA_SUCCESS: '@ENRUTA:UPDATE_RUTA_SUCCESS',
    UPDATE_RUTA_ERROR: '@ENRUTA:UPDATE_RUTA_ERROR',

    /************** PRODUCTO ******************/
    GET_PRODUCTOS_START: '@ENRUTA:GET_PRODUCTOS_START',
    GET_PRODUCTOS_SUCCESS: '@ENRUTA:GET_PRODUCTOS_SUCCESS',
    GET_PRODUCTOS_ERROR: '@ENRUTA:GET_PRODUCTOS_ERROR',

    DELETE_PRODUCTO_START: '@ENRUTA:DELETE_PRODUCTO_START',
    DELETE_PRODUCTO_SUCCESS: '@ENRUTA:DELETE_PRODUCTO_SUCCESS',
    DELETE_PRODUCTO_ERROR: '@ENRUTA:DELETE_PRODUCTO_ERROR',

    CREATE_PRODUCTO_START: '@ENRUTA:CREATE_PRODUCTO_START',
    CREATE_PRODUCTO_SUCCESS: '@ENRUTA:CREATE_PRODUCTO_SUCCESS',
    CREATE_PRODUCTO_ERROR: '@ENRUTA:CREATE_PRODUCTO_ERROR',

    VALIDAR_CODIGO_PRODUCTO_START: '@ENRUTA:VALIDAR_CODIGO_PRODUCTO_START',
    VALIDAR_CODIGO_PRODUCTO_SUCCESS: '@ENRUTA:VALIDAR_CODIGO_PRODUCTO_SUCCESS',
    VALIDAR_CODIGO_PRODUCTO_ERROR: '@ENRUTA:VALIDAR_CODIGO_PRODUCTO_ERROR',

    UPDATE_PRODUCTO_START: '@ENRUTA:UPDATE_PRODUCTO_START',
    UPDATE_PRODUCTO_SUCCESS: '@ENRUTA:UPDATE_PRODUCTO_SUCCESS',
    UPDATE_PRODUCTO_ERROR: '@ENRUTA:UPDATE_PRODUCTO_ERROR',
}