export default {
    ABORDO_TITLE: 'A bordo',
    EN_RUTA: 'En ruta',
    GUARDANDO: 'Guardando...',
    LISTA_CLIENTES_TITLE: 'Lista de Clientes',
    LISTA_PRODUCTOS_TITLE: 'Lista de Productos',
    REGISTRO_GUARDADO_TITLE: 'Nuevo registro',
    REGISTRO_ERROR_TITLE: 'Algo salio mal',
    REGISTRO_INVALIDO_TITLE: 'Registro inválido',
    REGISTRO_ACTUALIZADO_TITLE: 'Actualizar registro',
    REGISTRO_ELIMINADO_TITLE: 'Borrar registro',
    UBICACION_GUARDADO_TITLE: 'Ubicación',
    GALERIA_GUARDADO_TITLE: 'Galeria',
    GEOLOCALIZACION_CLIENTE_TITLE: 'Geolocalización del cliente',
    BTN_CERRAR_LABEL: 'Cerrar',
    BTN_GUARDAR_LABEL: 'Guardar',
    BTN_AGREGAR_LABEL: 'Agregar registro',
    BTN_SELECCIONAR_LABEL: 'Seleccionar',
    BTN_CANCELAR_LABEL: 'Cancelar',
}